

<?php
//{{block type="core/template" show_total="4" name="product_bestseller" as="product_bestseller" template="catalog/product/bestseller.phtml}}

$totalPerPage = ($this->show_total) ? $this->show_total : 6;
$visibility = array(
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                  );

$storeId = Mage::app()->getStore()->getId();

$_productCollection = Mage::getResourceModel('reports/product_collection')
						->addOrderedQty()
						->addAttributeToSelect('*')     
					    ->setStoreId($storeId)
                        ->addStoreFilter($storeId)	
					    ->addAttributeToFilter('visibility', $visibility)
						->setOrder('ordered_qty', 'desc')
						->addAttributeToSelect('status') 
						->setPageSize($totalPerPage);
Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_productCollection);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_productCollection);
Mage::getSingleton('catalog/product_visibility')->addVisibleInSearchFilterToCollection($_productCollection);


// //end if product is part of configurable product get first parent product
?>

<!--<div class="listing-type-grid  block">-->
<div class="clear_both"></div>
<div class="box best-selling">
	<h3>Best Selling Products</h3>
	<?php $_collectionSize = $_productCollection->count() ?>
		<table border="0" cellspacing="0">
			<tbody>
				<?php $_columnCount = 3; ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php if($i++%$_columnCount==0): ?>
				<tr class="odd">
				<?php endif; ?>
					 <td>			
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80, 108); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
						</a>
						<div class="product-description">
							<h5>
								<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
							</h5>
							
							<div>
							<span><?php				
			try{
				$categories = $_product->getCategoryIds();				
				$category = Mage::getModel('catalog/category')->load($categories[0]);
				echo 'See all '.'<a href="'.$category->getUrl().'" >'.$category->getName().'</a>';				
			} catch(Exception $e){}
			?></span></div>
							
						</div>
						
						
						<div class="clear"></div>
						
						

					</td>
					<?php if ($i%3==0 && $i!=$_collectionSize): ?>
				</tr>
					<?php endif ?>
					<?php endforeach ?>
					<?php for($i;$i%3!=0;$i++): ?>
						  <td class="empty">&nbsp;</td>
					<?php endfor ?>
					<?php if ($i%3==0): ?>
				</tr>
				<?php endif ?>
			</tbody>
		 </table>
    <script type="text/javascript">decorateTable('products-grid-table')</script>
    <div class="bottom-callout"></div>
</div>

